// Generated by LiveScript 1.3.1
(function(){
  var parse_sentence, parseSexp, target_sentence;
  parse_sentence = require('./parse_sentence').parse_sentence;
  parseSexp = require('./parse_sexp').parseSexp;
  target_sentence = 'This paper introduces architectural and interaction patternsfor integrating crowdsourced human contributions directlyinto user interfaces.';
  parse_sentence(target_sentence, 'en', function(sexp){
    var parsed;
    console.log(sexp);
    parsed = parseSexp(sexp);
    return console.log(parsed);
  });
}).call(this);
