// Generated by LiveScript 1.3.1
(function(){
  var jsonfile, patterns_dict, patterns_examples, patterns, i$, len$, pattern;
  jsonfile = require('jsonfile');
  patterns_dict = jsonfile.readFileSync('patterns_dict_tatoeba_eng.json');
  patterns_examples = jsonfile.readFileSync('patterns_examples_tatoeba_eng.json');
  patterns = Object.keys(patterns_dict);
  patterns.sort(function(x, y){
    return patterns_dict[x] - patterns_dict[y];
  });
  for (i$ = 0, len$ = patterns.length; i$ < len$; ++i$) {
    pattern = patterns[i$];
    console.log(pattern + ':' + patterns_dict[pattern] + ' [ex]: ' + JSON.stringify(patterns_examples[pattern]));
  }
}).call(this);
