// Generated by LiveScript 1.3.1
(function(){
  var jsonfile, word_counts, word_examples, words, i$, len$, word;
  jsonfile = require('jsonfile');
  word_counts = jsonfile.readFileSync('word_counts_tatoeba_eng.json');
  word_examples = jsonfile.readFileSync('word_examples_tatoeba_eng.json');
  words = Object.keys(word_counts);
  words.sort(function(x, y){
    return word_counts[x] - word_counts[y];
  });
  for (i$ = 0, len$ = words.length; i$ < len$; ++i$) {
    word = words[i$];
    console.log(word + ':' + word_counts[word] + ' [ex]: ' + JSON.stringify(word_examples[word]));
  }
}).call(this);
