// Generated by LiveScript 1.3.1
(function(){
  var fs, srt, asyncblock, jsonfile, request, querystring, lines_chinese, parse_trees, ref_translations;
  fs = require('fs');
  srt = require('srt');
  asyncblock = require('asyncblock');
  jsonfile = require('jsonfile');
  request = require('request');
  querystring = require('querystring');
  lines_chinese = [];
  parse_trees = {};
  ref_translations = {};
  srt('黑色社2以和为贵_sim_en.srt', function(err, data){
    return asyncblock(function(flow){
      var i$, ref$;
      for (i$ in ref$ = data) {
        (fn$.call(this, i$, ref$[i$]));
      }
      console.log(parse_trees);
      return jsonfile.writeFileSync('ref_translations.json', ref_translations);
      function fn$(num, subline){
        var subtext, numlines, ref$, chinese, english, getParse;
        subtext = subline.text.trim();
        numlines = subtext.split('\n').length;
        if (numlines !== 2) {
          throw new Exception('expected 2 lines: ' + subtext);
        }
        ref$ = subtext.split('\n'), chinese = ref$[0], english = ref$[1];
        getParse = function(text, callback){
          return request('http://geza.csail.mit.edu:3555/parse?' + querystring.stringify({
            lang: 'zh',
            sentence: chinese
          }), function(err, res, body){
            parse_trees[chinese] = body;
            return callback();
          });
        };
        console.log(chinese);
        lines_chinese.push(chinese);
        ref_translations[chinese] = english;
      }
    });
  });
}).call(this);
