// Generated by LiveScript 1.3.1
(function(){
  var request, querystring, parse_sentence, out$ = typeof exports != 'undefined' && exports || this;
  request = require('request');
  querystring = require('querystring');
  out$.parse_sentence = parse_sentence = function(sentence, lang, callback){
    return request('http://localhost:3555/parse?' + querystring.stringify({
      lang: lang,
      sentence: sentence
    }), function(err, res, body){
      return callback(body);
    });
  };
}).call(this);
