// Generated by LiveScript 1.3.1
(function(){
  var jsonfile, word_counts, words, word_ranks, i$, len$, idx, word, rank;
  jsonfile = require('jsonfile');
  word_counts = jsonfile.readFileSync('word_counts_tatoeba_eng.json');
  words = Object.keys(word_counts);
  words.sort(function(a, b){
    return word_counts[b] - word_counts[a];
  });
  word_ranks = {};
  for (i$ = 0, len$ = words.length; i$ < len$; ++i$) {
    idx = i$;
    word = words[i$];
    rank = idx + 1;
    console.log(word + ':' + rank);
    word_ranks[word] = rank;
  }
  jsonfile.writeFileSync('word_ranks_tatoeba_eng.json', word_ranks);
}).call(this);
