// Generated by LiveScript 1.3.1
(function(){
  var jsonfile, word_counts, words, i$, len$, word;
  jsonfile = require('jsonfile');
  word_counts = jsonfile.readFileSync('word_counts_tatoeba_eng.json');
  words = Object.keys(word_counts);
  words.sort(function(a, b){
    return word_counts[a] - word_counts[b];
  });
  for (i$ = 0, len$ = words.length; i$ < len$; ++i$) {
    word = words[i$];
    console.log(word + ':' + word_counts[word]);
  }
}).call(this);
